jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /mudanza
      session:
         timeout: 21600s

spring:
   datasource: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost/adn-ceiba?serverTimezone=America/Bogota&useSSL=false
      username: root
      password: root
      hikari:
         poolName: pool